version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - '3009:3306'
    environment:
      MYSQL_DATABASE: 'fpso_db'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

  web:
    container_name: 'web'
    build: .
    command: 'python manage.py runserver 0.0.0.0:8000'
    volumes:
      - '.:/code'
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8081:8000'
